name: libmpv
description: Dart bindings to libmpv.
homepage: https://github.com/alexmercerind/libmpv.dart
repository: https://github.com/alexmercerind/libmpv.dart
version: 0.0.1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  path: ^1.8.0
  ffi: ^1.0.1
  ffigen: ^4.1.2

dev_dependencies:
  lints: ^1.0.0

ffigen:
  name: MPV
  description: Dart bindings to libmpv.
  output: bin/generated/bindings.dart
  headers:
    entry-points:
      - headers/client.h
  dart-bool: true
